### ISSUE TITLE
大佬 怎么看是否重排成功

### ISSUE THREAD

**Issue by WadonLiu** [yulingtianxia/AppOrderFiles#3]
用System Trace 查看File Backed Page In次数?

**Comment by WadonLiu** [comment]
就是重排之后感觉启动速度没有变化

**Comment by yulingtianxia** [comment]
@WadonLiu 这个库是用于生成 order 文件的，后续流程也很简单，网上有很多文章介绍。

**Comment by WadonLiu** [comment]
大神口中的简单… 一点也不简单
以下文字送给跟我一样菜的抠脚的人
通过设置app.order文件,查看linkmap 发现 顺序确实提前了
<img width="900" alt="image" src="https://user-images.githubusercontent.com/12226706/64143170-799c6700-ce41-11e9-8f8e-f28b18fb3a2f.png">
参考链接 https://juejin.im/post/5d5a05255188251f4705fb8b
