### ISSUE TITLE
无法获取其他类的方法调用符合

### ISSUE THREAD

**Issue by syzhou1223** [yulingtianxia/AppOrderFiles#6]
这个只能获取到Main方法与Appdelegate里面的相关方法，ViewController以及其他类的调用方法都没有获取到。是我打开方式不对吗，比如在Demo里面的RootVC里面的ViewDidLoad添加一个新方法调用，就没有捕捉到。

**Comment by yulingtianxia** [comment]
这取决于你何时调用 'AppOrderFiles()' 啊

**Comment by syzhou1223** [comment]
我理解错了，谢谢提醒~
